let item_1 = 5;
let item_2 = 3;
console.log(item_1); 
console.log(item_2);

let item_3 = item_1 + item_2; 
console.log(item_3); 
 
let item_4 = "Yolochka"; 
console.log(item_4); 
let = +item_3 + item_4;  
let = item_3 * item_4;  

let item_5 = item_3; 
let item_6 = 15 ; 
let item_6_type =  (item_6, typeof item_6); 
console.log(item_6); 
console.log(item_6_type);
let item_7 = "item_6";
let item_7_type = item_7; 
console.log(item_7, typeof item_7_type,);  
 
 let age_1 = 10; 
 let age_2 = 18; 
 let age_3 = 60; 
  
 let result = age_1 < age_2;
 console.log("You don’t have access cause your age is ” + age_1 + “ It’s less then =",result);
 if(result){ 
    console.log(" if result =", result);
 } 
   
let result_1 =  age_1 >= age_2; 
let result_2 =  age_1 < age_3; 
console.log("Welcome  ! =", result_1); 
if(result_1){ 
console.log(" if result =", result_1); 
} 
console.log("Welcome  ! =", result_2); 
if(result_2){ 
console.log(" if result =", result_2);  
} 
 
let result_3 = age_1 > age_3; 
console.log("Keep calm and look Culture channel / ", "Technical work = ", result_3); 
if(result_3){  
    console.log( "if result =", result_3);

}